export interface track {
    id: string,
    name: string,
    content: string,
    url : string,
    status: string,
    date: string,
    book_id: string,
    chapter: string,
    synopsys: string,
    details: string,
    modules: Array<any>,
    slno: string,
    nameurdu : string,
    horizontal_img : string,
    logo : string,
    logo_min : string,
    fav : boolean,
    chapterurdu : string,
    bookname : string,
    audionameurdu : string,
    audioname : string,
    download : number,
    color : string,
    downloading : boolean,
    downloaded : boolean,
    fullpath : string,
    chapter_id : string,
    contentText : string,
    contentTextArabic : string
}
